SET(ENABLE_STRICT "OFF" CACHE STRING "" FORCE)
SET(ENABLE_PYTHON "OFF" CACHE STRING "" FORCE)

SET(HAVE_DIAGNOSTIC "ON" CACHE STRING "" FORCE)

SET(ENABLE_LZ4 "OFF" CACHE STRING "" FORCE)
SET(ENABLE_SNAPPY "OFF" CACHE STRING "" FORCE)
SET(ENABLE_ZLIB "OFF" CACHE STRING "" FORCE)
SET(ENABLE_ZSTD "OFF" CACHE STRING "" FORCE)

SET(HAVE_BUILTIN_EXTENSION_LZ4 "ON" CACHE STRING "" FORCE)
SET(HAVE_BUILTIN_EXTENSION_SNAPPY "ON" CACHE STRING "" FORCE)
SET(HAVE_BUILTIN_EXTENSION_SODIUM "ON" CACHE STRING "" FORCE)
SET(HAVE_BUILTIN_EXTENSION_ZLIB "ON" CACHE STRING "" FORCE)
SET(HAVE_BUILTIN_EXTENSION_ZSTD "ON" CACHE STRING "" FORCE)

# Export build commands to json file 
SET(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "" FORCE)

SET(CMAKE_TOOLCHAIN_FILE ON CACHE STRING "${CMAKE_SOURCE_DIR}/cmake/toolchains/mongodbtoolchain_stable_gcc.cmake" FORCE)
